//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sansm.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.contato = new HashSet<contato>();
            this.documento = new HashSet<documento>();
            this.endereco = new HashSet<endereco>();
            this.login = new HashSet<login>();
            this.sugestao = new HashSet<sugestao>();
            this.troca = new HashSet<troca>();
            this.venda = new HashSet<venda>();
        }
    
        public string idcliente { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> dt_nascimento { get; set; }
        public Nullable<int> idade { get; set; }
        public string genero { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
    
        public virtual ICollection<contato> contato { get; set; }
        public virtual ICollection<documento> documento { get; set; }
        public virtual ICollection<endereco> endereco { get; set; }
        public virtual ICollection<login> login { get; set; }
        public virtual ICollection<sugestao> sugestao { get; set; }
        public virtual ICollection<troca> troca { get; set; }
        public virtual ICollection<venda> venda { get; set; }
    }
}
