//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sansm.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class colaborador
    {
        public colaborador()
        {
            this.contato = new HashSet<contato>();
            this.documento = new HashSet<documento>();
            this.endereco = new HashSet<endereco>();
            this.login = new HashSet<login>();
            this.rh = new HashSet<rh>();
            this.salario = new HashSet<salario>();
        }
    
        public string idcolaborador { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> dt_nascimento { get; set; }
        public Nullable<int> idade { get; set; }
        public string genero { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
    
        public virtual ICollection<contato> contato { get; set; }
        public virtual ICollection<documento> documento { get; set; }
        public virtual ICollection<endereco> endereco { get; set; }
        public virtual ICollection<login> login { get; set; }
        public virtual ICollection<rh> rh { get; set; }
        public virtual ICollection<salario> salario { get; set; }
    }
}
