//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sansm.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class contato
    {
        public contato()
        {
            this.patrimonio = new HashSet<patrimonio>();
            this.sugestao = new HashSet<sugestao>();
        }
    
        public int idcontato { get; set; }
        public string telefonere { get; set; }
        public string telefonecel { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public string idcliente { get; set; }
        public string idcolaborador { get; set; }
        public Nullable<int> idfornecedor { get; set; }
        public Nullable<int> idestoque { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual colaborador colaborador { get; set; }
        public virtual fornecedor fornecedor { get; set; }
        public virtual estoque estoque { get; set; }
        public virtual ICollection<patrimonio> patrimonio { get; set; }
        public virtual ICollection<sugestao> sugestao { get; set; }
    }
}
