//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sansm.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        public int iddocumento { get; set; }
        public string cpf { get; set; }
        public string cnpj { get; set; }
        public string pis { get; set; }
        public string teleitor { get; set; }
        public string creservisrar { get; set; }
        public byte[] foto { get; set; }
        public string certidaons { get; set; }
        public Nullable<bool> comproresidencial { get; set; }
        public Nullable<bool> comproescolaridade { get; set; }
        public string idcliente { get; set; }
        public string idcolaborador { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual colaborador colaborador { get; set; }
    }
}
