//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sansm.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class endereco
    {
        public endereco()
        {
            this.patrimonio = new HashSet<patrimonio>();
        }
    
        public int idendereco { get; set; }
        public string cep { get; set; }
        public string rua { get; set; }
        public string complemento1 { get; set; }
        public string complemento2 { get; set; }
        public string numero { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public string idcliente { get; set; }
        public string idcolaborador { get; set; }
        public Nullable<int> idfornecedor { get; set; }
        public Nullable<int> idestoque { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual colaborador colaborador { get; set; }
        public virtual fornecedor fornecedor { get; set; }
        public virtual estoque estoque { get; set; }
        public virtual ICollection<patrimonio> patrimonio { get; set; }
    }
}
