//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sansm.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class fornecedor
    {
        public fornecedor()
        {
            this.contato = new HashSet<contato>();
            this.endereco = new HashSet<endereco>();
            this.patrimonio = new HashSet<patrimonio>();
        }
    
        public int idfornecedor { get; set; }
        public string nome { get; set; }
        public string tipo { get; set; }
        public string obs { get; set; }
        public Nullable<int> idproduto { get; set; }
    
        public virtual ICollection<contato> contato { get; set; }
        public virtual ICollection<endereco> endereco { get; set; }
        public virtual produto produto { get; set; }
        public virtual ICollection<patrimonio> patrimonio { get; set; }
    }
}
