//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sansm.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int idlogin { get; set; }
        public string departamento { get; set; }
        public string acesso { get; set; }
        public string senha { get; set; }
        public string idcliente { get; set; }
        public string idcolaborador { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual colaborador colaborador { get; set; }
    }
}
