//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sansm.database.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sanmsEntities : DbContext
    {
        public sanmsEntities()
            : base("name=sanmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cliente> cliente { get; set; }
        public DbSet<colaborador> colaborador { get; set; }
        public DbSet<contato> contato { get; set; }
        public DbSet<despesa> despesa { get; set; }
        public DbSet<documento> documento { get; set; }
        public DbSet<endereco> endereco { get; set; }
        public DbSet<estoque> estoque { get; set; }
        public DbSet<fornecedor> fornecedor { get; set; }
        public DbSet<login> login { get; set; }
        public DbSet<patrimonio> patrimonio { get; set; }
        public DbSet<produto> produto { get; set; }
        public DbSet<receita> receita { get; set; }
        public DbSet<rh> rh { get; set; }
        public DbSet<salario> salario { get; set; }
        public DbSet<sugestao> sugestao { get; set; }
        public DbSet<troca> troca { get; set; }
        public DbSet<venda> venda { get; set; }
    }
}
