//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sansm.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class receita
    {
        public int idreceita { get; set; }
        public Nullable<decimal> vendaaprazo { get; set; }
        public Nullable<decimal> vendaervico { get; set; }
        public Nullable<decimal> nmreceitaadicional { get; set; }
        public Nullable<decimal> vlreceitaacionla { get; set; }
    }
}
