//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sansm.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class rh
    {
        public int idrh { get; set; }
        public Nullable<System.DateTime> ferias_dtentrada { get; set; }
        public Nullable<System.DateTime> ferias_dtsaida { get; set; }
        public Nullable<bool> ativo { get; set; }
        public Nullable<System.DateTime> dt_contratacao { get; set; }
        public Nullable<System.DateTime> dt_demissao { get; set; }
        public Nullable<System.DateTime> falta { get; set; }
        public string idcolaborador { get; set; }
    
        public virtual colaborador colaborador { get; set; }
    }
}
