//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sansm.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class salario
    {
        public int idsalario { get; set; }
        public Nullable<decimal> salarioliquido { get; set; }
        public Nullable<decimal> salariobruto { get; set; }
        public Nullable<decimal> acrescimos { get; set; }
        public Nullable<decimal> decrescimos { get; set; }
        public Nullable<System.DateTime> mesalteracao { get; set; }
        public string conta { get; set; }
        public string banco { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public string idcolaborador { get; set; }
    
        public virtual colaborador colaborador { get; set; }
    }
}
