//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sansm.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sugestao
    {
        public int idsugestao { get; set; }
        public Nullable<int> nota { get; set; }
        public Nullable<int> idcontato { get; set; }
        public string idcliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual contato contato { get; set; }
    }
}
