//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sap.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class contato
    {
        public int id { get; set; }
        public string telefonere { get; set; }
        public string telefonecel { get; set; }
        public string email { get; set; }
        public string nick { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
