//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sap.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class endereco
    {
        public int id { get; set; }
        public string cep { get; set; }
        public string rua { get; set; }
        public string complemento1 { get; set; }
        public string complemento2 { get; set; }
        public string numero { get; set; }
        public string nick { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
