//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sap.Database.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class estudoEntities : DbContext
    {
        public estudoEntities()
            : base("name=estudoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agenda> agenda { get; set; }
        public virtual DbSet<contato> contato { get; set; }
        public virtual DbSet<endereco> endereco { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<pesquisa> pesquisa { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
